#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - xclip
        - zsh

    # TODO: Does not work in playbook, since it asks for password confirmation
    # - name: set zsh as default shell
    #   shell: chsh -s /usr/bin/zsh

    - name: clone oh my zsh
      git: repo=git@github.com:robbyrussell/oh-my-zsh.git
           dest=~/.oh-my-zsh
           update=no
