#!/usr/bin/env ansible-playbook
---
- name: configures ZSH
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} state=present
      sudo: yes
      when: no_sudo is not defined
      with_items:
        - fzf
        - xclip
        - zplug
        - zsh

    # TODO: Does not work in playbook, since it asks for password confirmation
    # - name: set zsh as default shell
    #   shell: chsh -s /usr/bin/zsh
